# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/flash-nbdev',
                'doc_host': 'https://imflash217.github.io',
                'git_url': 'https://github.com/imflash217/flash-nbdev',
                'lib_path': 'flash_nbdev'},
  'syms': {'flash_nbdev.core': {'flash_nbdev.core.foo': ('core.html#foo', 'flash_nbdev/core.py')}}}
